# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850607315ccabf5fa6e38ebc72b73e7b6f5fcbea923e0bf47467409317ff9a2b997e1cb5abb0dbf1a426f9cc6292381a6fd918e8e235ab4693493e076ce13fca

test:
  secret_key_base: 99b0a4a0f5c306e31842157676f5b4cf30d106a3242974088779e885932551d88985487fd59eb33ae7278b04c39d0f4766b411195554e50b781d593226ac2325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
